name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Actualizado a v4
    - name: set up JDK 17
      uses: actions/setup-java@v4  # Actualizado a v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: android

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      continue-on-error: true

    - name: Build with Gradle
      run: ./gradlew assembleDebug
      continue-on-error: true

    - name: Upload APK
      uses: actions/upload-artifact@v4  # ESTA ES LA CORRECCIÃ“N CLAVE
      with:
        name: MatrixPlayer-APK
        path: app/build/outputs/apk/debug/app-debug.apk
